server:
   port: 8081
spring:
   application:
      name: alita
   datasource:
      url: jdbc:mysql://localhost:3306/alita?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      druid:
         stat-view-servlet:
            login-username: admin
            login-password: 123456
